config:
  logLevel: trace
  service: |
    [SERVICE]
        Daemon Off
        Flush 5
        Log_Level debug
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
  
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*playlist*.log
        Tag kube.*
        Parser docker
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On
  
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Index fluent-bit
        Type _doc
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls Off
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix playlist-app
        Retry_Limit False
        Suppress_Type_Name On
  
  parsers: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
