# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: mongodb-credentials
#   namespace: {{ .Release.Namespace }}
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: SecretStore
#   target:
#     name: mongodb-secret
#     creationPolicy: Owner
#   data:
#   - secretKey: MONGODB_URI
#     remoteRef:
#       key: playlist-app-secrets
#       property: MONGODB_URI
#   - secretKey: MONGODB_USERNAME
#     remoteRef:
#       key: playlist-app-secrets
#       property: MONGODB_USERNAME
#   - secretKey: MONGODB_PASSWORD
#     remoteRef:
#       key: playlist-app-secrets
#       property: MONGODB_PASSWORD

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: playlists
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_URI
  - secretKey: MONGODB_USERNAME
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_USERNAME
  - secretKey: MONGODB_PASSWORD
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_PASSWORD