apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: mongodb-passwords
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_PASSWORD
  - secretKey: mongodb-root-password
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_PASSWORD
  - secretKey: mongodb-replica-set-key
    remoteRef:
      key: playlist-app-secrets
      property: MONGODB_PASSWORD
