
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd                   
spec:
  project: default                    
  sources:            
  - repoURL: "https://charts.bitnami.com/bitnami"
    chart: elasticsearch
    targetRevision: 21.1.0
    helm:
      valueFiles:
      - $values/infra-apps/values/elasticsearch-values.yaml
  - repoURL: https://github.com/sara-golombeck/gitops.git
    targetRevision: main
    ref: values
  destination:                         
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:                          
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true