# logging/elasticsearch/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: "22.0.4"
    helm:
      values: |
        global:
          kibanaEnabled: false  # נתחיל בלי Kibana עד שElasticsearch יעבוד
        
        master:
          masterOnly: false
          replicaCount: 1  # התחלנו עם 1 במקום 2
          heapSize: "1g"   # פחות זיכרון להתחלה
          resources:
            requests:
              cpu: "0.5"
              memory: "2Gi"  # פחות זיכרון להתחלה
            limits:
              cpu: "1"
              memory: "4Gi"  # פחות זיכרון להתחלה
          readinessProbe:
            enabled: false
          livenessProbe:
            enabled: false
            
        data:
          replicaCount: 0
          
        ingest:
          enabled: false
          
        coordinating:
          replicaCount: 0
          
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi  # התחלנו עם פחות
          storageClassName: "gp2"  # שיניתי לgp2 במקום gp3
          
        persistence:
          labels:
            enabled: true
            
        security:
          enabled: false  # בלי security להתחלה!
          
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true