apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: elasticsearch
    targetRevision: 21.1.0
    helm:
      values: |
        global:
          kibanaEnabled: true
        master:
          masterOnly: false
          replicaCount: 2
          heapSize: "2g"
          resources:
            requests:
              cpu: "0.5"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "6Gi"
          readinessProbe:
            enabled: false
          livenessProbe:
            enabled: false
        data:
          replicaCount: 0
        ingest:
          enabled: false
        coordinating:
          replicaCount: 0
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
          storageClassName: "gp3"
        persistence:
          labels:
            enabled: true
        security:
          enabled: true
          elasticPassword: "9sRLSqZOhtUpSpyn"
          tls:
            restEncryption: true
            autoGenerated: true
        kibana:
          ingress:
            enabled: false
          elasticsearch:
            security:
              tls:
                enabled: true
                verificationMode: "none"
                usePemCerts: false
              auth:
                enabled: true
                kibanaPassword: "9sRLSqZOhtUpSpyn"
                createSystemUser: true
                elasticsearchPasswordSecret: "elasticsearch"
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true