# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: elasticsearch
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: "https://charts.bitnami.com/bitnami"
#     chart: elasticsearch
#     targetRevision: 21.1.0
#     helm:
#       values: |
#         global:
#           kibanaEnabled: true
#         master:
#           masterOnly: false
#           replicaCount: 1
#           heapSize: "1g"
#           resources:
#             requests:
#               cpu: "0.5"
#               memory: "2Gi"
#             limits:
#               cpu: "1"
#               memory: "3Gi"
#           readinessProbe:
#             enabled: false
#           livenessProbe:
#             enabled: false
#         data:
#           replicaCount: 0
#         ingest:
#           enabled: false
#         coordinating:
#           replicaCount: 0
#         volumeClaimTemplate:
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 30Gi
#           storageClassName: "gp3"
#         persistence:
#           labels:
#             enabled: true
#         security:
#           enabled: true
#           elasticPassword: "9sRLSqZOhtUpSpyn"
#           tls:
#             restEncryption: true
#             autoGenerated: true
#         kibana:
#           ingress:
#             enabled: false
#           elasticsearch:
#             security:
#               tls:
#                 enabled: true
#                 verificationMode: "none"
#                 usePemCerts: false
#               auth:
#                 enabled: true
#                 kibanaPassword: "9sRLSqZOhtUpSpyn"
#                 createSystemUser: true
#                 elasticsearchPasswordSecret: "elasticsearch"
#           livenessProbe:
#             enabled: false
#           readinessProbe:
#             enabled: false
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: logging
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - ServerSideApply=true
#       - CreateNamespace=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  sources:            
  - repoURL: "https://charts.bitnami.com/bitnami"
    chart: elasticsearch
    targetRevision: 21.1.0
    helm:
      valueFiles:
      - $values/values/elasticsearch-values.yaml
  - repoURL: https://github.com/sara-golombeck/gitops.git
    targetRevision: main
    ref: values                             