apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 7.17.3  # גרסה יציבה יותר
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        
        esConfig:
          elasticsearch.yml: |
            cluster.name: "docker-cluster"
            network.host: 0.0.0.0
            discovery.type: single-node
            xpack.security.enabled: false
            
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"
          resources:
            requests:
              storage: 5Gi  # קטן יותר
              
        service:
          type: ClusterIP
          
        persistence:
          enabled: true
          
        # Memory settings פשוטים
        esJavaOpts: "-Xmx512m -Xms512m"
        
        # הסרת security context שעלול לגרום לבעיות
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true