
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets
#   namespace: argocd
# spec:
#   destination:
#     namespace: external-secrets
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: external-secrets
#     helm:
#       values: |
#         serviceAccount:
#           create: true
#           name: external-secrets
#           annotations:
#             eks.amazonaws.com/role-arn: "arn:aws:iam::793786247026:role:sara-portfolio-cluster-external-secrets-role"
#     repoURL: https://charts.external-secrets.io
#     targetRevision: 0.17.0
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
#     - ServerSideApply=true
#     - Validate=false
#     - PrunePropagationPolicy=foreground
#     - PruneLast=true
#     - RespectIgnoreDifferences=true
#     - ApplyOutOfSyncOnly=true



apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: "https://charts.external-secrets.io"
    chart: external-secrets
    targetRevision: 0.17.0
    helm:
      values: |
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::793786247026:role:sara-portfolio-cluster-external-secrets-role"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true    # <-- הוסף את זה!
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true