# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets
#   namespace: argocd
# spec:
#   destination:
#     namespace: external-secrets
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: external-secrets
#     repoURL: https://charts.external-secrets.io
#     targetRevision: 0.10.4
#     helm:
#       values: |
#         serviceAccount:
#           create: true
#           name: external-secrets
#           annotations:
#             eks.amazonaws.com/role-arn: "arn:aws:iam::793786247026:role:sara-portfolio-cluster-external-secrets-role"
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true

# # apiVersion: external-secrets.io/v1beta1
# # kind: ClusterSecretStore
# # metadata:
# #   name: aws-secrets-manager
# # spec:
# #   provider:
# #     aws:
# #       service: SecretsManager
# #       region: ap-south-1
# #       auth:
# #         jwt:
# #           serviceAccountRef:
# #             name: external-secrets
# #             namespace: external-secrets



apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.4
    helm:
      values: |
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::793786247026:role:sara-portfolio-cluster-external-secrets-role"
        auth:
          webIdentity
            audience:""
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true