
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io/foreground
# spec:
#   project: default
#   source:
#     repoURL: "https://charts.external-secrets.io"
#     chart: external-secrets
#     targetRevision: 0.17.0
#     helm:
#       values: |
#         serviceAccount:
#           create: false
#           name: external-secrets
#           annotations:
#             eks.amazonaws.com/role-arn: "arn:aws:iam::980921758549:role:sara-portfolio-cluster-external-secrets-role"
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: external-secrets
#   syncPolicy:
#     automated:
#       allowEmpty: false
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - ServerSideApply=true   
#     - Validate=true
#     - CreateNamespace=true
#     - PrunePropagationPolicy=foreground
#     - PruneLast=true



apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:                                          
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
  - repoURL: "https://charts.external-secrets.io"
    chart: external-secrets
    targetRevision: 0.17.0
    helm:
      valueFiles:
      - $values/infra-apps/values/external-secrets-values.yaml
  - repoURL: "https://github.com/sara-golombeck/gitops.git"
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true   
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true