apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: elasticsearch-secrets
 namespace: logging
 annotations:
   argocd.argoproj.io/sync-wave: "1"
spec:
 refreshInterval: 1h
 secretStoreRef:
   name: aws-secrets-manager
   kind: ClusterSecretStore
 target:
   name: elasticsearch-secret
   creationPolicy: Owner
 data:
 - secretKey: ELASTICSEARCH_PASSWORD
   remoteRef:
     key: playlist-app-secrets          
     property: ELASTICSEARCH_PASSWORD
 - secretKey: KIBANA_PASSWORD
   remoteRef:
     key: playlist-app-secrets          
     property: KIBANA_PASSWORD