# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: fluentbit
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://fluent.github.io/helm-charts
#     chart: fluent-bit
#     targetRevision: 0.21.7
#     helm:
#       values: |
#         config:
#           service: |
#             [SERVICE]
#                 Flush 1
#                 Log_Level info
#                 HTTP_Server On
#                 HTTP_Port 2020

#           inputs: |
#             [INPUT]
#                 Name tail
#                 Path /var/log/containers/*playlist-app*.log
#                 Tag kube.playlist.*
#                 Parser docker
#                 Mem_Buf_Limit 50MB

#           filters: |
#             [FILTER]
#                 Name kubernetes
#                 Match kube.*
#                 Merge_Log On
#                 K8S-Logging.Parser On

#             [FILTER]
#                 Name parser
#                 Match kube.playlist.*
#                 Key_Name log
#                 Parser json
#                 Reserve_Data On

#           outputs: |
#             [OUTPUT]
#                 Name es
#                 Match kube.playlist.*
#                 Host elasticsearch-master.logging.svc.cluster.local
#                 Port 9200
#                 Index playlist-logs
#                 Logstash_Format On
#                 Logstash_Prefix playlist-app
#                 Logstash_DateFormat %Y.%m.%d

#           parsers: |
#             [PARSER]
#                 Name json
#                 Format json
#                 Time_Key asctime
#                 Time_Format %Y-%m-%dT%H:%M:%S

#         resources:
#           requests:
#             cpu: "100m"
#             memory: "128Mi"
#           limits:
#             cpu: "200m"
#             memory: "256Mi"
            
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: logging
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.21.7
    helm:
      values: |
        logLevel: info
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level debug
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On
                Trace_Error On
                
          inputs: |
            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On
            [INPUT]
                Name tail
                Path /var/log/containers/*nginx*.log
                Parser docker
                Tag nginx.*
            [INPUT]
                Name tail
                Path /var/log/containers/*_rando_*.log
                Parser docker
                Tag kube.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On
            [FILTER]
                Name parser
                Match nginx.*
                Key_Name log
                Parser nginx_ingress_parser
                Reserve_Data On
                
          outputs: |
            [OUTPUT]
                Name es
                Match host.*
                Index fluent-bit
                Type _doc
                Host elasticsearch-master.logging.svc.cluster.local
                Port 9200
                tls On
                tls.verify Off
                HTTP_User elastic
                HTTP_Passwd 9sRLSqZOhtUpSpyn
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
                Suppress_Type_Name On
            [OUTPUT]
                Name es
                Match nginx.*
                Index fluent-bit
                Type _doc
                Host elasticsearch-master.logging.svc.cluster.local
                Port 9200
                tls On
                tls.verify Off
                HTTP_User elastic
                HTTP_Passwd 9sRLSqZOhtUpSpyn
                Logstash_Format On
                Logstash_Prefix nginx
                Retry_Limit False
                Suppress_Type_Name On
            [OUTPUT]
                Name es
                Match kube.*
                Index fluent-bit
                Type _doc
                Host elasticsearch-master.logging.svc.cluster.local
                Port 9200
                tls On
                tls.verify Off
                HTTP_User elastic
                HTTP_Passwd 9sRLSqZOhtUpSpyn
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On
                
          customParsers: |
            [PARSER]
                Name docker
                Format json
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                Time_Keep On
            [PARSER]
                Name json
                Format json
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                Time_Keep On
            [PARSER]
                Name nginx_ingress_parser
                Format regex
                Regex ^[^ ]+ [^ ]+ [^ ]+ (?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<host>[^ ]*) (?<server_protocol>[^ ]*)
                Time_Key time
                Time_Format %d/%b/%Y:%H:%M:%S %z

        resources:
          requests:
            cpu: "100m"
            memory: "512M"
          limits:
            cpu: "1000m"
            memory: "1Gi"
            
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true