# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ingress-controller
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: ingress-nginx
#     repoURL: https://kubernetes.github.io/ingress-nginx
#     targetRevision: 4.10.1
#     helm:
#       values: |
#         controller:
#           resources:
#             requests:
#               cpu: 200m
#               memory: 256Mi
#             limits:
#               cpu: 500m
#               memory: 512Mi
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: ingress-nginx
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - RespectIgnoreDifferences=true
#     managedNamespaceMetadata:
#       labels:
#         app: ingress-nginx
#         managed-by: argocd


# try

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.1
    helm:
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
            limits:
              cpu: 200m
              memory: 180Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true