apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"
        
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            
        service:
          type: ClusterIP
          port: 5601
          
        # אופציונלי - רק אם יש לך דומיין
        # ingress:
        #   enabled: true
        #   className: nginx
        #   hosts:
        #     - host: kibana.your-domain.com
        #       paths:
        #         - path: /
        #           pathType: Prefix
          
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true