{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "playlist-app.fullname" . }}-metrics
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      {{- include "playlist-app.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.name }}
    path: {{ .Values.monitoring.path }}
{{- end }}
