{{- if .Values.auth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.fullname" . }}-init
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  init-mongo.js: |
    db.createUser({
      user: "{{ .Values.auth.username }}",
      pwd: "{{ .Values.auth.password }}",
      roles: [
        {
          role: "readWrite",
          db: "{{ .Values.auth.database }}"
        }
      ]
    });
{{- end }}